name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Debug - Print Working Directory
        run: pwd

      - name: Install Dependencies
        run: npm install

  build:
    runs-on: ubuntu-latest
    needs: start

    steps:
      - name: Debug - Print Working Directory
        run: pwd

      - name: Set Project Directory
        run: echo "::set-env name=PROJECT_DIR::/home/runner/work/accessibleUI"

      - name: Run Styleguide Build
        run: npm --prefix ${{ env.PROJECT_DIR }} run styleguide:build

      - name: Build Production Webpack Code
        run: npm --prefix ${{ env.PROJECT_DIR }} run build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Run Tests
        run: npm --prefix ${{ env.PROJECT_DIR }} run test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./styleguide
